### PR TITLE
Fix Light Mode

### PR DESCRIPTION
**Pull request by tanguy-fgl**
I took the opportunity to change the light mode that stung the eyes too much, I grayed it a little to make it more comfortable. I also changed the theme change button to make it more accessible.
image
The logo that is present on the image is not integrated to the pull request

### CODE REVIEW

**Comment by tanguy-fgl** [comment]
The image represents the light mode on a French MOFHY (which is not the case for the pull request)

**Review by greenreader9 — APPROVED** [review]
Looks good!

**Review by jaikt — APPROVED** [review]
Awesome!

**Comment by mahtab2003** [comment]
Will not dark mode being affected?

**Comment by greenreader9** [comment]
Just implemented this for real on my site, I have to say, your color choices are impressive.

**Pull request merged**
