### PR TITLE
Add Google ReCapcha Functionality

### PR DESCRIPTION
**Pull request by greenreader9**
It's here! Added Google ReCaptcha functionality on login and signup pages. Because I'm lazy, you're going to have to add the keys manually (It's only 4 files, not bad at all). I also updated the install instructions to make them easier to follow, and to guide new users in Google ReCaptcha setup.

### CODE REVIEW

**Comment by jaikrishna-tavva9** [comment]
So is this fully functional? I have tried implementing but no luck, it does not verify.

**Comment by jaikt** [comment]
Ok, i implemented it on my site, it is working amazingly. Thank you @greenreader9 for saving my day from bots ✌️

**Comment by greenreader9** [comment]
Glad to hear it!

**Comment by jaikt** [comment]
you could try centering the div element for more user satisfaction - `<center><div class="g-recaptcha" data-sitekey="YOUR SITE KEY HERE"></div></center>`..

**Comment by greenreader9** [comment]
> you could try centering the div element for more user satisfaction - `<center><div class="g-recaptcha" data-sitekey="YOUR SITE KEY HERE"></div></center>`..

Before suggesting code, please make sure it is valid.
>The ```<center>``` is a deprecated HTML tag and not supported in HTML5.

**Comment by jaikt** [comment]
Ok, so just add the center module of Halfmoon CSS in class  = `text-center`

**Comment by greenreader9** [comment]
@mahtab2003, is there something wrong with this pull, or are you waiting to accept it for anouther reason?

**Comment by mahtab2003** [comment]
I'm waiting for mofhy addon guide one it is done this request will be merged

**Pull request closed without merging**
