### PR TITLE
prevent sql injections

### PR DESCRIPTION
**Pull request by jaikt**
Added `mysqli_real_escape_string`. More commits when I find files that are vulnerable. Some could also help me give the list of files!

### CODE REVIEW

**Review by greenreader9 — CHANGES_REQUESTED** [review]
Did you test this? I don't think it will work as I don't thing $connection is defined here.

**Comment by jaikt** [comment]
It is `$connect` and should work. What makes you think that?

**Comment by greenreader9** [comment]
Wait, so is it tested or not? Since $connect is never defined in that file, I do not know if it will work. You should test everything before you make a PR.

**Comment by jaikt** [comment]
> Wait, so is it tested or not? Since $connect is never defined in that file, I do not know if it will work. You should test everything before you make a PR.

I think you forgot the MOFHY code. It is define in `Connect.php` which is included on line 1.
~~~
include __DIR__.'/Connect.php';
~~~

**Comment by greenreader9** [comment]
PHP can be weird sometimes, and (in my testing at least) include files outside the calling file are not seen.

**Pull request merged**
